apiVersion: apps/v1
kind: Deployment 
metadata:
  name: with-node-affinity
spec:
  replicas: 2
  selector:
    matchLabels:
      type: ssdPods
  template:
    metadata:
      labels:
        type: ssdPods
    spec:
      volumes:
      - name: html-volume
        emptyDir: {}
      
      initContainers:
      - name: install
        image: busybox:1.28
        command:
        - sh
        - -c
        - echo "Hello from ssdPods running on k8snode" > /usr/share/nginx/html/index.html
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
 
      
      containers:
      - name: nginxcontainer
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: nginxport
          containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - ssd
---
apiVersion: v1
kind: Service
metadata:
  name: ssdpodservice
spec:
  type: NodePort
  selector:
    type: ssdPods
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
