apiVersion: apps/v1
kind: Deployment 
metadata:
  name: with-pod-anti-afinity
spec:
  replicas: 2
  selector:
    matchLabels:
      type: not-ssdPods
  template:
    metadata:
      labels:
        type: not-ssdPods
    spec:
      volumes:
      - name: html-volume
        emptyDir: {}
      
      initContainers:
      - name: install
        image: busybox:1.28
        command:
        - sh
        - -c
        - echo "Hello from not-ssdPods running on k8snode3 automatically since it dosen't have  label (type=ssd)" > /usr/share/nginx/html/index.html
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
 
      
      containers:
      - name: nginxcontainer
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: nginxport
          containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: type
                operator: In
                values:
                - ssdPods # Make sure to put the label of the pods not the node
            topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: Service
metadata:
  name: notssdpodservice
spec:
  type: NodePort
  selector:
    type: not-ssdPods
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
