apiVersion: v1
kind: Pod
metadata:
  name: sharedstorage-alpine
  labels:
    name: sharedstorage
spec:
  volumes:
  - name: cache-volume
    emptyDir: {}
  containers:
  - name: alpine1
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep", "3600"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache1

  - name: alpine2
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["sleep", "3600"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache2