apiVersion: apps/v1
kind: Deployment
metadata:
  name: nignxwebsite
spec:
  selector:
    matchLabels:
      appname: bizwebsite
  template:
    metadata:
      labels:
        appname: bizwebsite
    spec: 
      containers:
      - name: nginx
        image: nginx
        ports: 
        - containerPort: 80
        resources:
#          limits: 
#            cpu: 500m
          requests:
            cpu: 125m
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    run: php-apache
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    appname: bizwebsite