apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pvc
spec:
  storageClassName: manual  # Corrected this line
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
