apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv
spec:
  storageClassName: manual  # Corrected this line
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/apache
