apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deploy
  namespace: team
spec:
  selector:
      matchLabels:
        app: busybox-pod
  template:
    metadata:
      labels:
        app: busybox-pod
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sh
        - -c
        - sleep 3600
        resources:
          requests:
            memory: "100Mi"  
