apiVersion: v1 
kind: LimitRange 
metadata:
  name: mem-limit-range
  namespace: limited
spec:
  limits:
  - default:
      memory: 125Mi
    defaultRequest:
      memory: 100Mi
    max: 
      memory: 500Mi 
    type: Container